name: arch workflow
run-name: ${{ github.actor }} is building ${{ github.repository }} using GitHub Actions ğŸš€
on: [push, pull_request]
jobs:
  build_arch:
    runs-on: archlinux-multilib-devel
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: update arch repo and system
        run: |
          pacman -Syyu
      - name: install build deps
        run: |
          pacman -S base base-devel curl libevent asciidoc
      - name: build and test
        run: |
          ./waf configure
          ./waf build
          ./build/saldl "https://google.com"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
